---
   - name: Download Zip and Wget.
     yum:
       name: [wget, zip]
       state: present

   - name: Download SonarQube Binaries
     get_url:
      url: "{{ sonar_download_url }}"
      dest: "{{ sonar_install_directory }}"
     become: yes
     
   - name: Expand SonarQube Binaries
     unarchive:
        src: "{{sonar_install_directory}}/{{sonar_archive}}"
        dest: "{{sonar_install_directory}}"
        copy: no

   - name: "Remove SonarQube Archive"
     file:
        path: "{{sonar_install_directory}}/{{sonar_archive}}"
        state: absent  

   - name: Provide full Permissions to sonarqube
     file:
       path: "{{sonarqube}}"
       state: directory
       recurse: yes
       owner: "{{sonar_user}}"
       group: "{{sonar_group}}"
       mode: 0777
     tags:
     - permission

   - name: Running SonarQube
     shell: sh sonar.sh start
     become_user: "{{sonar_user}}"
     args:
        chdir: "{{sonar_daemon_dir}}"
     register: Running_status
     tags:
     - Running

   - debug: var=Running_Status.stdout
     tags:
     - Running
