---
   - name: 1.Download Jenkins Repo
     get_url:
          url: "{{repo_url}}"
          dest: "{{repo_dest}}"

   - name: Import Jenkins Key
     rpm_key:
        key: "{{rpm_key}}"
        state: present

   - name: Install Jenkins
     yum:
       name: jenkins
       state: present

   - name: Start & Enable Jenkins
     systemd:
        name: jenkins
        state: started
        enabled: true

   - name: Sleep for 30 seconds and continue with play
     wait_for: timeout=30

   - name: Get init password Jenkins
     shell: cat /var/lib/jenkins/secrets/initialAdminPassword
     changed_when: false
     register: passwdforjenkins
     tags:
       - passwd

   - name: Print init password Jenkins
     debug:
        var: passwdforjenkins.stdout
     tags:
        - passwd
