---
sonar_archive: sonarqube-{{ sonar_version }}.zip
sonar_version: 7.6
sonar_download_url: https://binaries.sonarsource.com/Distribution/sonarqube/{{sonar_archive}}
sonar_install_directory: /opt/
sonarqube: "{{ sonar_install_directory }}/sonarqube-{{ sonar_version }}"
sonar_daemon_dir: "{{ sonar_install_directory }}sonarqube-{{ sonar_version }}/bin/linux-x86-64/"
####chnage this part###############
sonar_user: azam     #Your_Username
sonar_group: azam  #Your_Group_name
